remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "My Portfolio"
description: "Writings and data analysis projects."


nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Literature reviews"
    url: "/Literature reviews"
